package com.budgetapple.pidrobe.webapp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DisplayOutfitDesign extends HorizontalLayout {
    protected Label temperatureLabel;
    protected Label suggestionLabel;
    protected Button selectSavedPreset;
    protected Button saveNewPreset;
    protected Button backButton;
    protected VerticalLayout verticalLayoutOutfit;
    protected HorizontalLayout horizontalLayoutUpperBody;
    protected VerticalLayout verticalLayoutUpper1;
    protected VerticalLayout verticalLayoutUpper2;

    public DisplayOutfitDesign() {
        Design.read(this);
    }




}
